### ISSUE TITLE
[Android] Alert popup

### ISSUE THREAD

**Issue by jeremybarbet** [jeremybarbet/Statiks#10]
Replace `AlertIOS` with the common component for both iOS and Android https://github.com/JeremDsgn/Statiks/blob/master/src/screens/settings/components/Input.js#L74

**Comment by JeremDsgn** [comment]
https://sentry.io/jeremy-barbet/statiks/issues/435130151/

**Comment by jeremybarbet** [comment]
Fixed in v2.1.4
